# Generated by Django 3.2 on 2021-04-24 18:53

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_createpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='img',
            field=models.ImageField(null=True, upload_to=post.models.custom_upload_to),
        ),
    ]
