# Generated by Django 3.2 on 2021-04-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210424_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['-created'], 'verbose_name': 'Anime', 'verbose_name_plural': 'Animes'},
        ),
        migrations.AlterField(
            model_name='createpost',
            name='category',
            field=models.ManyToManyField(related_name='Categorias', to='post.Categories'),
        ),
    ]
