# Generated by Django 3.2 on 2021-05-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210425_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='category',
            field=models.ManyToManyField(to='post.Categories'),
        ),
    ]
