# Generated by Django 3.2 on 2021-05-03 20:33

import cap.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0006_alter_createpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=cap.models.custom_upload_to)),
                ('numeroCapitulo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Capitulo')),
                ('cap', models.FileField(upload_to=cap.models.custom_upload_to, verbose_name='Video')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.createpost')),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
                'ordering': ['-created', 'title'],
            },
        ),
    ]
